services:

  mock-app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    volumes:
      - shared_db:/data

    ports:
      - "8000:8000"

  automation:
    build: .

    depends_on:
      - mock-app

    environment:
      TEST_ENV: docker

    volumes:
      - shared_db:/data
      - ./allure-results:/app/allure-results
      - ./reports:/app/reports

    command: >
      pytest
      -m smoke

volumes:
  shared_db: