name: Regression

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Containers
        run: docker compose build

      - name: Execute Regression Suite
        run: |
          docker compose run --rm \
            -e TEST_ENV=docker \
            automation \
            pytest -m regression

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results